config/routes.rb
Gmap::Application.routes.draw do

  resources :users

  resource :session, :only => [:new, :create, :destroy]
  
  
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

 

  resources :outlets

  
   root :to => "characters#index"
  

  resources :characters
  

  

end

app/models/outlet.rb
class Outlet < ActiveRecord::Base
  attr_accessible :address, :category, :description, :latitude, :longitude, :name, :phone
  
   acts_as_gmappable :process_geocoding => false
  
  # Outlets associated with users
  belongs_to  :user
  
  
  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow
    "<h2>#{name}</h2><br/><h3>#{address}</h3>"

  end


  def gmaps4rails_marker_picture
    {
        #{}"picture" => "/images/#{name}.jpg",
        "width" => "25",
        "height" => "39",

    }
  end

  def gmaps4rails_sidebar
    "<span>#{latitude}</span>" #put whatever you want here
  end


  def gmaps4rails_title
    "yo gmaps"
  end
  
end

app/controllers/outlets_controller.rb
class OutletsController < ApplicationController
  
  
  # before_filter :authenticate_user!, :except => :index
  # GET /outlets
  # GET /outlets.json
  def index
    @outlets = Outlet.all
    @json = Outlet.all.to_gmaps4rails

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @outlets }
    end
  end

  # GET /outlets/1
  # GET /outlets/1.json
  def show
    @outlet = Outlet.find(params[:id])
    @json = Outlet.find(params[:id]).to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @outlet }
    end
  end

  # GET /outlets/new
  # GET /outlets/new.json
  def new
    @outlet = Outlet.new
    @json = Outlet.all.to_gmaps4rails

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @outlet }
    end
  end

  # GET /outlets/1/edit
  def edit
    @outlet = Outlet.find(params[:id])
    @json = Outlet.find(params[:id]).to_gmaps4rails
   
  end

  # POST /outlets
  # POST /outlets.json
  def create
    @outlet = Outlet.new(params[:outlet])

    respond_to do |format|
      if @outlet.save
        format.html { redirect_to @outlet, notice: 'Outlet was successfully created.' }
        format.json { render json: @outlet, status: :created, location: @outlet }
      else
        format.html { render action: "new" }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /outlets/1
  # PUT /outlets/1.json
  def update
    @outlet = Outlet.find(params[:id])
    @json = Character.all.to_gmaps4rails

    respond_to do |format|
      if @outlet.update_attributes(params[:outlet])
        format.html { redirect_to @outlet, notice: 'Outlet was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @outlet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /outlets/1
  # DELETE /outlets/1.json
  def destroy
    @outlet = Outlet.find(params[:id])
    @outlet.destroy

    respond_to do |format|
      format.html { redirect_to outlets_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/outlets_helper.rb
module OutletsHelper
end

app/views/outlets/_form.html.erb
<%= form_for(@outlet) do |f| %>
  <% if @outlet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@outlet.errors.count, "error") %> prohibited this outlet from being saved:</h2>

      <ul>
      <% @outlet.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :category %><br />
    <%= f.text_field :category %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br />
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br />
    <%= f.text_field :longitude %>
  </div>

<br/>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
<%= gmaps4rails(@json) %>


<% content_for :scripts do %>
<script type="text/javascript" charset="utf-8">
   var markersArray = [];
   
   // On click, clear markers, place a new one, update coordinates in the form
   Gmaps.map.callback = function() {
       google.maps.event.addListener(Gmaps.map.serviceObject, 'click', function(event) {
           clearOverlays();
   //Gmaps4Rails.clear_markers(); //supposed to clear previous marker
           placeMarker(event.latLng);
   setFormLocation(event.latLng); //my attempt
           updateFormLocation(event.latLng); // update
       });
   };
   
   
   // Add a marker with an open infowindow
   function placeMarker(latLng) {
       var marker = new google.maps.Marker({
           position: latLng,
           map: Gmaps.map.serviceObject,
           draggable: true // can this be set to false in the search result view?
   
       });
   
   
   function setFormLocation(lagLng){
   $("#outlet_latitude").val(latLng.lat());
   $('#outlet_longitude').val(latLng.lng());
   
   }            // Update form attributes with given coordinates
       function updateFormLocation(latLng) {
           $("#outlet_latitude").val(latLng.lat());
           $('#outlet_longitude').val(latLng.lng());
          					      //$('#character_attributes_gmaps_zoom').val(Gmaps.map.serviceObject.getZoom());
       }
   
       markersArray.push(marker);
       // Set and open infowindow
       var infowindow = new google.maps.InfoWindow({
           content: '<div class="popup"><h2>Hello!</h2><p>Drag me and adjust the zoom level.</p>' // need to allow this to be set from a text field
       });
   
       infowindow.open(Gmaps.map.serviceObject,marker);
   
       // Listen to drag & drop 
       google.maps.event.addListener(marker, 'dragend', function() {
   // map.setZoom(3);
           updateFormLocation(this.getPosition());
   //Gmaps4Rails.clear_markers();
       });
   }
   
   // Removes the overlays from the map
   function clearOverlays() {
       if (markersArray) {
           for (var i = 0; i < markersArray.length; i++ ) {
               markersArray[i].setMap(null);
           }
       }
       markersArray.length = 0;
   }
</script>
<% end %>

app/views/outlets/edit.html.erb
<h1>Editing outlet</h1>

<%= render 'form' %>

<%= link_to 'Show', @outlet %> |
<%= link_to 'Back', outlets_path %>

app/views/outlets/index.html.erb
<h1>Listing Outlets</h1>

<%= form_tag outlets_path, :method =>'Get' do %>
<p>
	<%= text_field_tag :search%>
	<%= submit_tag "Search"%>
	</p>
	<% end %>
	
<table>
  <tr>
    <th>Name</th>
    <th>Category</th>
    <th>Description</th>
    <th>Address</th>
    <th>Phone</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @outlets.each do |outlet| %>
  <tr>
    <td><%= outlet.name %></td>
    <td><%= outlet.category %></td>
    <td><%= outlet.description %></td>
    <td><%= outlet.address %></td>
    <td><%= outlet.phone %></td>
    <td><%= outlet.latitude %></td>
    <td><%= outlet.longitude %></td>



	<td><%= link_to 'Show', outlet %></td>
	
    

	  </tr>
	<% end %>
	</table>
	<ul id="markers_list">  </ul>




<%= link_to 'New Outlet', new_outlet_path %>
<br/>
<br/>

app/views/outlets/new.html.erb
<h1>New outlet</h1>

<%= render 'form' %>

<%= link_to 'Back', outlets_path %>

app/views/outlets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @outlet.name %>
</p>

<p>
  <b>Category:</b>
  <%= @outlet.category %>
</p>

<p>
  <b>Description:</b>
  <%= @outlet.description %>
</p>

<p>
  <b>Address:</b>
  <%= @outlet.address %>
</p>

<p>
  <b>Phone:</b>
  <%= @outlet.phone %>
</p>

<p>
  <b>Latitude:</b>
  <%= @outlet.latitude %>
</p>

<p>
  <b>Longitude:</b>
  <%= @outlet.longitude %>
</p>
<%= gmaps4rails(@json) %>


<% if can? :update, @outlet %>
<%= link_to 'Edit', edit_outlet_path(@outlet) %> 
<% end%>
<% if can? :destroy, @outlet %>
<td><%= link_to 'Destroy', outlet, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>
<% end %>

<%= link_to 'Back', outlets_path %>