config/routes.rb
Gmap::Application.routes.draw do

  resources :users

  resource :session, :only => [:new, :create, :destroy]
  
  
  match 'login' => 'sessions#new', :as => :login
  match 'logout' => 'sessions#destroy', :as => :logout
  match 'signup' => 'users#new', :as => :signup
  match 'activate/:activation_code' => 'users#activate', :as => :activate, :activation_code => nil

 

  resources :outlets

  
   root :to => "characters#index"
  

  resources :characters
  

  

end

app/models/character.rb
class Character < ActiveRecord::Base
  # character model is company or outlet profile
  # will have deals (like individual posts which can be searched by user)
  
  #character will become locations or profile
  #belongs to :user / outlet
  # Has_many :offers??
  # see 3:11 railscast elastic search part 1



  attr_accessible :address, :gmaps, :latitude, :longitude, :name

  acts_as_gmappable :process_geocoding => false
  
  # Tire added to model to facilitate elastic search
  # See railscast elastic search 3:11 pt 1
  
  include Tire::Model::Search
  include Tire::Model::Callbacks
  

  def gmaps4rails_address
    address
  end

  def gmaps4rails_infowindow
    "<h2>#{name}</h2><br/><h3>#{address}</h3>"

  end


  def gmaps4rails_marker_picture
    {
        #{}"picture" => "/images/#{name}.jpg",
        "width" => "25",
        "height" => "39",

    }
  end

  def gmaps4rails_sidebar
    "<span>#{latitude}</span>" #put whatever you want here
  end


  def gmaps4rails_title
    "yo gmaps"
  end

 

end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
  #before_filter  :login_required #function provided by authenticated system

  # GET /characters
  # GET /characters.json
  # index needs to be selective (ie. all characters in dublin 2)
  def index
    if params[:search]
     @characters = Character.find(:all, :conditions => ['name LIKE ?', "%#{params[:search]}%"])
   
   else
         @characters = Character.find(:all)

    @time = Time.now

    @characters = Character.all

    @json = Character.all.to_gmaps4rails

    @files = Dir.glob('*')

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @characters }
    end
  end
end


  # GET /characters/1
  # GET /characters/1.json
  # the show could be used to display the discount profile page to the user after selecting from the list
  def show
    @character = Character.find(params[:id])
    @json = Character.find(params[:id]).to_gmaps4rails

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @character }
    end
  end

  # GET /characters/new
  # GET /characters/new.json
  def new
    @character = Character.new
    @json = Character.all.to_gmaps4rails

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @character }
    end
  end

  # GET /characters/1/edit
  def edit
    @character = Character.find(params[:id])
    @json = Character.find(params[:id]).to_gmaps4rails
  end

  # POST /characters
  # POST /characters.json
  def create
    @character = Character.new(params[:character])

    respond_to do |format|
      if @character.save
        format.html { redirect_to @character, :notice => 'Character was successfully created.' }
        format.json { render :json => @character, :status => :created, :location => @character }
      else
        format.html { render :action => "new" }
        format.json { render :json => @character.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /characters/1
  # PUT /characters/1.json
  def update
    @character = Character.find(params[:id])
    @json = Character.all.to_gmaps4rails
    respond_to do |format|
      if @character.update_attributes(params[:character])
        flash[:success] = "Character's updated."
        format.html { redirect_to @character, :notice => 'Character was successfully updated.' }
        format.json { head :no_content }
        redirect_to character_path(@character)
      else
        format.html { render :action => "edit" }
        format.json { render :json => @character.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /characters/1
  # DELETE /characters/1.json
  def destroy
    @character = Character.find(params[:id])
    @character.destroy

    respond_to do |format|
      format.html { redirect_to characters_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/views/characters/_form.html.erb
<%= form_for(@character) do |f| %>
<% if @character.errors.any? %>
<div id="error_explanation" xmlns="http://www.w3.org/1999/html">
   <h2><%= pluralize(@character.errors.count, "error") %> prohibited this character from being saved:</h2>
   <ul>
      <% @character.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
   </ul>
</div>
<% end %>
<div class="field">
   <%= f.label :Business_Name %><br />
   <%= f.text_field :name ,  :placeholder=>"Enter your company name"%>
</div>
<div class="field">
   <%= f.label :address %><br />
   <%= f.text_field :address,  :placeholder=>"Enter your company address" %>
</div>

<div class="field">
   <%= f.label :longitude %><br />
   <%= f.text_field :longitude %>
</div>
<div class="field">
   <%= f.label :latitude %><br />
   <%= f.text_field :latitude %>
</div>

<div class="actions">
   <%= f.submit %>
</div>
<% end %>
<div>
   <%= gmaps4rails(@json) %>
</div>

<% content_for :scripts do %>
<script type="text/javascript" charset="utf-8">
   var markersArray = [];
   
   // On click, clear markers, place a new one, update coordinates in the form
   Gmaps.map.callback = function() {
       google.maps.event.addListener(Gmaps.map.serviceObject, 'click', function(event) {
           clearOverlays();
   //Gmaps4Rails.clear_markers(); //supposed to clear previous marker
           placeMarker(event.latLng);
   setFormLocation(event.latLng); //my attempt
           updateFormLocation(event.latLng); // update
       });
   };
   
   
   // Add a marker with an open infowindow
   function placeMarker(latLng) {
       var marker = new google.maps.Marker({
           position: latLng,
           map: Gmaps.map.serviceObject,
           draggable: true // can this be set to false in the search result view?
   
       });
   
   		function setFormLocation(lagLng){
   		$("#character_latitude").val(latLng.lat());
   		$('#character_longitude').val(latLng.lng());
   
   }            // Update form attributes with given coordinates
       function updateFormLocation(latLng) {
           $("#character_latitude").val(latLng.lat());
           $('#character_longitude').val(latLng.lng());
          					      //$('#character_attributes_gmaps_zoom').val(Gmaps.map.serviceObject.getZoom());
       }
   
       markersArray.push(marker);
       // Set and open infowindow
       var infowindow = new google.maps.InfoWindow({
           content: '<div class="popup"><h2>Hello!</h2><p>Drag me and adjust the zoom level.</p>' // need to allow this to be set from a text field
       });
   
       infowindow.open(Gmaps.map.serviceObject,marker);
   
       // Listen to drag & drop 
       google.maps.event.addListener(marker, 'dragend', function() {
   // map.setZoom(3);
           updateFormLocation(this.getPosition());
   //Gmaps4Rails.clear_markers();
       });
   }
   
   // Removes the overlays from the map
   function clearOverlays() {
       if (markersArray) {
           for (var i = 0; i < markersArray.length; i++ ) {
               markersArray[i].setMap(null);
           }
       }
       markersArray.length = 0;
   }
</script>
<% end %>

app/views/characters/edit.html.erb
<h1>Editing character</h1>

<%= render 'form' %>

<%= link_to 'Show', @character %> |
<%= link_to 'Back', outlets_path %>

app/views/characters/index.html.erb
<h1 xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
	 <h1>Listing Chars</h1>

<%= form_tag characters_path, :method =>'Get' do %>
<p>
	<%= text_field_tag :search %>
	<%= submit_tag "Search" %>
	</p>
	<% end %>


<p>This page should be for admin only</p>

<p>Type some keywords to search</p>
<table>
  <tr>
    <th>Name</th>
    <th>Address</th>
    <th>Longitude</th>
    <th>Latitude</th>
    <th></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @characters.each do |character| %>
  <tr>
    <td><%= character.name %></td>
    <td><%= character.address %></td>
    <td><%= character.longitude %></td>
    <td><%= character.latitude %></td>
    

    <td><%= link_to 'Show', character %></td>
    <td><%= link_to 'Edit', edit_character_path(character) %></td>
    <td><%= link_to 'Destroy', character, :method => :delete, :data => { :confirm => 'Are you sure?' } %></td>

  </tr>
<% end %>
</table>

<ul id="markers_list">  </ul>

<br />
<hr>

<%= link_to 'New Character', new_character_path %>
<br/>
<br/>




<p>
<%= @time %>
</p>

app/views/characters/new.html.erb
<h1>Register your deal</h1>

<%= render 'form' %>

<%= link_to 'Back', characters_path %>

app/views/characters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @character.name %>
</p>

<p>
  <b>Address:</b>
  <%= @character.address %>
</p>

<p>
  <b>Longitude:</b>
  <%= @character.longitude %>
</p>

<p>
  <b>Latitude:</b>
  <%= @character.latitude %>
</p>

<p>
  <b>Gmaps:</b>
  <%= @character.gmaps %>
</p>

<%= gmaps4rails(@json) %>



<%= link_to 'Edit', edit_character_path(@character) %> |
<%= link_to 'Back', characters_path %>

app/views/characters/transfer.html.erb
<h1>Hi</h1>

this page is for transplant whenever the plumbing is figured out